"""create data

Revision ID: 04e08525db4e
Revises: 
Create Date: 2022-06-22 12:43:43.622071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04e08525db4e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daftarkomunipertama', sa.Column('nama', sa.String(length=50), nullable=True))
    op.add_column('daftarkomunipertama', sa.Column('nama_pemandian', sa.String(length=50), nullable=True))
    op.add_column('daftarkomunipertama', sa.Column('tempat_lahir', sa.String(length=20), nullable=True))
    op.add_column('daftarkomunipertama', sa.Column('tgl_lahir', sa.String(length=20), nullable=True))
    op.add_column('daftarkomunipertama', sa.Column('tempat_pemandian', sa.String(length=50), nullable=True))
    op.add_column('daftarkomunipertama', sa.Column('tgl_pemandian', sa.String(length=20), nullable=True))
    op.add_column('daftarkomunipertama', sa.Column('nama_ayah', sa.String(length=50), nullable=True))
    op.add_column('daftarkomunipertama', sa.Column('nama_ibu', sa.String(length=50), nullable=True))
    op.add_column('daftarkomunipertama', sa.Column('alamat', sa.Text(), nullable=True))
    op.add_column('daftarkomunipertama', sa.Column('wilayah', sa.Text(), nullable=True))
    op.add_column('daftarkomunipertama', sa.Column('lingkungan', sa.Text(), nullable=True))
    op.add_column('daftarkomunipertama', sa.Column('telepon', sa.String(length=15), nullable=True))
    op.add_column('daftarkomunipertama', sa.Column('sekolah', sa.String(length=30), nullable=True))
    op.add_column('daftarkomunipertama', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('daftarkomunipertama', sa.Column('keterangan', sa.String(length=20), nullable=True))
    op.create_foreign_key(None, 'daftarkomunipertama', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'daftarkomunipertama', type_='foreignkey')
    op.drop_column('daftarkomunipertama', 'keterangan')
    op.drop_column('daftarkomunipertama', 'user_id')
    op.drop_column('daftarkomunipertama', 'sekolah')
    op.drop_column('daftarkomunipertama', 'telepon')
    op.drop_column('daftarkomunipertama', 'lingkungan')
    op.drop_column('daftarkomunipertama', 'wilayah')
    op.drop_column('daftarkomunipertama', 'alamat')
    op.drop_column('daftarkomunipertama', 'nama_ibu')
    op.drop_column('daftarkomunipertama', 'nama_ayah')
    op.drop_column('daftarkomunipertama', 'tgl_pemandian')
    op.drop_column('daftarkomunipertama', 'tempat_pemandian')
    op.drop_column('daftarkomunipertama', 'tgl_lahir')
    op.drop_column('daftarkomunipertama', 'tempat_lahir')
    op.drop_column('daftarkomunipertama', 'nama_pemandian')
    op.drop_column('daftarkomunipertama', 'nama')
    # ### end Alembic commands ###
