"""create data

Revision ID: f50bfdcee1bf
Revises: 
Create Date: 2022-07-01 14:43:54.035939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f50bfdcee1bf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daftarbaptisbayi', sa.Column('jadwal', sa.String(length=20), nullable=True))
    op.add_column('daftarbaptisdewasa', sa.Column('jadwal', sa.String(length=20), nullable=True))
    op.add_column('daftarkomunipertama', sa.Column('jadwal', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daftarkomunipertama', 'jadwal')
    op.drop_column('daftarbaptisdewasa', 'jadwal')
    op.drop_column('daftarbaptisbayi', 'jadwal')
    # ### end Alembic commands ###
